Fix bug where Slack API returns 400 due to large entities
port-labs/port-sender pull request #20
Opened 2024-07-05 09:29 UTC by lordsarcastic

When the number of repositories are large enough, the message generated overshoots the message limit per block for Slack's API. This causes a 400 error. To fix this, I implemented a functionality to automatically break them into chunks of 20 entities per block. A side effect is an extra space between chunks as seen in the image below:

![image](https://github.com/port-labs/port-sender/assets/33290249/697cdceb-a906-4fe4-b3d6-ac26a857670b)

2024-07-07 10:24 UTC, Tankilevitch requested changes

2024-07-07 10:24 UTC, Tankilevitch commented on generators/slack.py
> +
```suggestion
```

2024-07-07 10:24 UTC, Tankilevitch commented on generators/slack.py
> +            )
I feel like we need to batch them based on size of supported message size and not relying on number of entities. 
As we can have long entities names that will break the "20" entities that you have defined.

2024-07-22 11:56 UTC, matan84 requested changes
Left two comments

2024-07-22 11:56 UTC, matan84 commented on utils.py
> +def batch_items(items: list[Any], batch_size: int):
Where is this used?

2024-07-22 11:56 UTC, matan84 commented on generators/slack.py
> +    SCORECARD_ENTITIES_BATCH_SIZE = 20
This isn't used anywhere

2024-07-22 12:07 UTC, matan84 requested changes
More changes

2024-07-22 12:07 UTC, matan84 commented on utils.py
> +from typing import Any
Remove import

2024-07-22 12:07 UTC, matan84 commented on generators/slack.py
> +                current_entities.pop()
Add comment here explaining what and why are you doing this

2024-07-22 12:07 UTC, matan84 commented on generators/slack.py
> +            batch_count = 0
Add comments here

2024-07-22 14:37 UTC, matan84 approved these changes
One last comment

2024-07-22 14:37 UTC, matan84 commented on generators/slack.py
> +            MAX_MESSAGE_BLOCK_SIZE_FOR_TITLE = (
```suggestion
            max_message_block_size_for_entities = (
```

2024-07-22 14:46 UTC, merged